### ISSUE TITLE
feat: new format call `Properties Files`

### ISSUE THREAD

**Issue by Pengap** [apitable/apitable-settings-generator#3]
- [x] New format: Properties Files
- [x] Provide new ways to use
- [x] Complete unit testing

### Format: `Properties Files`

`.properties` is a file extension for files that store configurable parameters for an application. They can also store strings for internationalization and localization, and such files are called Property Resource Bundles.

Usually the format of the file contents is `key=value`.

So the files need to be saved according to the different languages when they are generated

You have this JSON config file `config.json`:
```typescript
[
  {
    "dirName": "./generated",
    "fileName": "i18n_*.properties",
    "languageList"?: [
      "zh_CN",
      "en_US"
    ],
    "tables": [
      {
        "datasheetId": "dstbUhd5coNXQoXFD8",
        "datasheetName": "i18n",
        "format": "properties-files",
        "params"?: {...}
      }
    ]
  }
]
```

> **Note:** We have provided an interesting parameter `languageList` here.
> when you have many internationalized language settings, then you can specify parameters to control the list of accepted languages.
>
> example：
>  languageList:["zh_CN"]

Run APITable Settings Generator (`asg`):
```bash
# run in bash
npx apitable-settings-generator --config config.json --token ${HERE_IS_YOUR_APITABLE_TOKEN}
```

Generated settings `i18n_en_US.properties`:
```properties
long_text=Hello apitable
short_text=Hello
```

Generated settings `i18n_zh_CN.properties`:
```properties
long_text=你好 apitable
short_text=你好
```

Tips：
1. When you have the following list of languages

```
i18n_en_US.properties
i18n_zh_CN.properties
```

When you only need the `zh_CN` configuration package, you can now use the `languageList` attribute to control the output files, e.g.

```
...
languageList: ['zh-CN']
...
```
Now only the language file `i18n_zh_CN.properties` you specified will be output

**Comment by mr-kelly** [comment]
Can the "language" use *?

**Comment by Pengap** [comment]
> Can the "language" use *?

The reason for using variables here is to generate them to avoid changing the file name again, which can be done in one step.

If you use `*`, if the generated file name is `i18n.en_US. properties`

But if I use spring i18n, I actually want to get the file name `i18n_en_US. properties` without modifying the configuration.
